### ISSUE TITLE
Migrate content

### ISSUE THREAD

**Issue by nate-double-u** [fluent/fluent-bit-website-very-old#4]
Move pages and information from the old site to the new.

**Comment by nate-double-u** [comment]
What content needs to be migrated?

It looks like the main site https://fluentbit.io/ needs to be brought over.
- [x] Where is the source for this website currently?

Does the docs site, https://docs.fluentbit.io/ powered by gitbook, need to be brought over as well?
- [x] current repo: https://github.com/fluent/fluent-bit-docs

**Comment by nate-double-u** [comment]
Source content has been moved here:
https://github.com/fluent/fluentbit-website-v3

**Comment by edsiper** [comment]
fyi: documentation is not necessary, we just link from the website to gitbook

**Comment by nate-double-u** [comment]
Closing as stale (https://cncfservicedesk.atlassian.net/browse/CNCFSD-559 has also been closed)
