### ISSUE TITLE
Collect graphic design artifacts

### ISSUE THREAD

**Issue by nate-double-u** [fluent/fluent-bit-website-very-old#5]
Logos, word marks, glyphs, etc., anything we need to bring over from the old site.

**Comment by nate-double-u** [comment]
Some Fluentd assets can be found here: https://github.com/cncf/artwork/blob/master/projects/fluentd but I'm not sure if there are any _fluent bit_ assets there.

**Comment by edsiper** [comment]
@caniszczyk should we upload Fluent Bit logos to cncf/artwork  ?

**Comment by nate-double-u** [comment]
Closing as stale (https://cncfservicedesk.atlassian.net/browse/CNCFSD-559 has also been closed)
