### ISSUE TITLE
Close fluent/fluent-bit-website repo

### ISSUE THREAD

**Issue by nate-double-u** [fluent/fluent-bit-website-very-old#9]
I suggest closing this repo as stale, https://cncfservicedesk.atlassian.net/browse/CNCFSD-559 was closed with a new website so I don't think this is required anymore.

**Comment by edsiper** [comment]
thanks for the follow up, yup let's close it

**Comment by nate-double-u** [comment]
I just looked, I don't think I have permissions to do it myself, so someone on your team will need to do the final close. 🙂
